name: CI Pipeline for Microservices

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'

    # Paso 3: Instalar dependencias y compilar el proyecto de MicroserviceUsuarios
    - name: Build MicroserviceUsuarios with Maven
      working-directory: ./Viajes-Global--Develop/MicroserviceUsuarios  # Directorio del microservicio Usuarios
      run: mvn clean install -DskipTests

    # Paso 4: Ejecutar pruebas en MicroserviceUsuarios
    - name: Run tests for MicroserviceUsuarios
      working-directory: ./Viajes-Global--Develop/MicroserviceUsuarios
      run: mvn test

    # Paso 5: Instalar dependencias y compilar el proyecto de MicroserviceReservas
    - name: Build MicroserviceReservas with Maven
      working-directory: ./Viajes-Global--Develop/MicroserviceReservas  # Directorio del microservicio Reservas
      run: mvn clean install -DskipTests

    # Paso 6: Ejecutar pruebas en MicroserviceReservas
    - name: Run tests for MicroserviceReservas
      working-directory: ./Viajes-Global--Develop/MicroserviceReservas
      run: mvn test

    # Paso 7: Instalar dependencias y compilar el proyecto de MicroservicePagos
    - name: Build MicroservicePagos with Maven
      working-directory: ./Viajes-Global--Develop/MicroservicePagos  # Directorio del microservicio Pagos
      run: mvn clean install -DskipTests

    # Paso 8: Ejecutar pruebas en MicroservicePagos
    - name: Run tests for MicroservicePagos
      working-directory: ./Viajes-Global--Develop/MicroservicePagos
      run: mvn test

    # Paso 9: Instalar dependencias y compilar el proyecto de MicroservicePromociones
    - name: Build MicroservicePromociones with Maven
      working-directory: ./Viajes-Global--Develop/MicroservicePromociones  # Directorio del microservicio Promociones
      run: mvn clean install -DskipTests

    # Paso 10: Ejecutar pruebas en MicroservicePromociones
    - name: Run tests for MicroservicePromociones
      working-directory: ./Viajes-Global--Develop/MicroservicePromociones
      run: mvn test

    # Paso 11: Instalar dependencias y compilar el proyecto de MicroserviceCarritoCompras
    - name: Build MicroserviceCarritoCompras with Maven
      working-directory: ./Viajes-Global--Develop/MicroserviceCarritoCompras  # Directorio del microservicio CarritoCompras
      run: mvn clean install -DskipTests

    # Paso 12: Ejecutar pruebas en MicroserviceCarritoCompras
    - name: Run tests for MicroserviceCarritoCompras
      working-directory: ./Viajes-Global--Develop/MicroserviceCarritoCompras
      run: mvn test
