name: CI Pipeline for MicroservicePromociones

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar JDK 21 (puedes cambiar la versión si usas otra)
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    # Paso 3: Instalar dependencias y compilar el proyecto (sin ejecutar pruebas en este paso)
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Paso 4: Ejecutar pruebas
    - name: Run tests
      run: mvn test
